import typescriptParser from '@typescript-eslint/parser';

export default [
  {
    files: ['**/*.{ts,tsx,js,jsx}'],
    languageOptions: {
      parser: typescriptParser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        __DEV__: 'readonly',
        console: 'readonly',
        process: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        window: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        Promise: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        NodeJS: 'readonly',
        React: 'readonly',
      },
    },
    rules: {
      // 모든 규칙을 off로 설정하여 에러 방지
      'no-unused-vars': 'off',
      'no-console': 'off',
      'no-undef': 'off',
      'no-const-assign': 'off',
      'no-redeclare': 'off',
      'no-unreachable': 'off',
      'no-empty': 'off',
      'no-constant-condition': 'off',
      'no-debugger': 'off',
      'no-dupe-args': 'off',
      'no-dupe-keys': 'off',
      'no-duplicate-case': 'off',
      'no-ex-assign': 'off',
      'no-extra-boolean-cast': 'off',
      'no-extra-semi': 'off',
      'no-func-assign': 'off',
      'no-inner-declarations': 'off',
      'no-invalid-regexp': 'off',
      'no-irregular-whitespace': 'off',
      'no-obj-calls': 'off',
      'no-regex-spaces': 'off',
      'no-sparse-arrays': 'off',
      'no-unexpected-multiline': 'off',
      'use-isnan': 'off',
      'valid-typeof': 'off',
    },
  },
  {
    ignores: [
      '**/node_modules/**',
      '**/.expo/**',
      '**/dist/**',
      '**/build/**',
      '**/*.config.js',
      '**/*.config.mjs',
      '**/*.config.ts',
      '**/babel.config.js',
      '**/metro.config.js',
      '**/coverage/**',
      '**/.next/**',
      '**/out/**',
      '**/android/**',
      '**/ios/**',
      '**/.git/**',
      '**/playwright-report/**',
      '**/test-results/**',
    ],
  },
];