# Railway 프로젝트 전체 설정
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

# 환경별 서비스 설정
[[services]]
name = "glimpse-server"
source = "server/"

[services.build]
buildCommand = "npm run build"

[services.deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/v1/health"

[[services]]  
name = "glimpse-mobile"
source = "mobile/"

[services.build]
buildCommand = "npx expo export:web"

[services.deploy]
startCommand = "npx serve dist"

[[services]]
name = "glimpse-web"
source = "web/"

[services.build]
buildCommand = "npm run build"

[services.deploy]
startCommand = "npx serve dist"

[[services]]
name = "glimpse-admin" 
source = "admin/"

[services.build]
buildCommand = "npm run build"

[services.deploy]
startCommand = "npm run start"