#!/bin/bash

# Vercel 환경변수 설정 스크립트
echo "======================================"
echo "   Vercel 환경변수 설정 가이드"
echo "======================================"
echo ""
echo "Vercel Dashboard에서 다음 환경변수를 설정해주세요:"
echo "https://vercel.com/[your-username]/glimpse-server/settings/environment-variables"
echo ""
echo "필수 환경변수:"
echo "---------------"
echo ""
echo "1. DATABASE_URL (Railway PostgreSQL)"
echo "   예: postgresql://postgres:[password]@[host]:5432/railway"
echo ""
echo "2. DIRECT_URL (Railway PostgreSQL Direct)"
echo "   예: postgresql://postgres:[password]@[host]:5432/railway"
echo ""
echo "3. JWT_SECRET"
echo "   예: your-super-secret-jwt-key-change-this-in-production"
echo ""
echo "4. CLERK_SECRET_KEY"
echo "   값: sk_test_ahquE3eARWKYofKL7BQoMLfHl7474tiTuMSm1twG4C"
echo ""
echo "5. NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
echo "   값: pk_test_bGlrZWQtZG9nLTkzLmNsZXJrLmFjY291bnRzLmRldiQ"
echo ""
echo "선택적 환경변수 (기능별로 필요시):"
echo "-----------------------------------"
echo "- AWS_ACCESS_KEY_ID"
echo "- AWS_SECRET_ACCESS_KEY"
echo "- AWS_REGION"
echo "- AWS_S3_BUCKET_NAME"
echo "- FIREBASE_PROJECT_ID"
echo "- FIREBASE_CLIENT_EMAIL"
echo "- FIREBASE_PRIVATE_KEY"
echo "- SENDGRID_API_KEY"
echo "- EMAIL_FROM"
echo ""
echo "테스트용 최소 환경변수 설정 명령:"
echo "================================"
echo ""
echo "vercel env add DATABASE_URL production"
echo "vercel env add DIRECT_URL production"
echo "vercel env add JWT_SECRET production"
echo "vercel env add CLERK_SECRET_KEY production"
echo "vercel env add NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY production"
echo ""
echo "설정 후 재배포:"
echo "vercel --prod"