apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "glimpse-*"
    basicAuth: false
    isDefault: false
    jsonData:
      esVersion: "8.11.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: log_level

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    editable: true